# Generated by Django 4.1.5 on 2023-03-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers_categorysubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscriber',
        ),
    ]
